### ISSUE TITLE
Gigaspace version and some other question.

### ISSUE THREAD

**Issue by climacs** [xap/xap-docker#2]
1. i'm using a license version 
July 2 2019 xxxxxxxxxxx@xxxxxxxxxxxxPREMIUM^10.0XAPPremium%UNBOUND+UNLIMITED//WAN
can I run this on version 12.0.1 (xap-docker).
2. is there any issue running xap-docker on a
   redhat 7.3 with Docker version 17.04.0-ce, build 4845c56
   I installed it by the book specially the steps you guys/gals provided.
and i got some error or message after the dockerfile command.
----
Step 7/21 : ADD http://d3a0pn6rx5g9yg.cloudfront.net/sites/default/files/private/product/gigaspaces-xap-premium-${XAP_VERSION}-${XAP_MILESTONE}-b${XAP_BUILD_NUMBER}.zip /tmp/g                                   igaspaces-xap-premium-${XAP_VERSION}-${XAP_MILESTONE}-b${XAP_BUILD_NUMBER}.zip
Get http://d3a0pn6rx5g9yg.cloudfront.net/sites/default/files/private/product/gigaspaces-xap-premium-12.0.1-ga-b16600.zip: dial tcp: lookup d3a0pn6rx5g9yg.cloudfront.net on 172                                   .31.0.2:53: no such host
----
3. after the dockerfile i got this 2 images only and no other images is created.
   REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
<none>              <none>              8d6d282c9543        16 minutes ago      643MB
java                8                   d23bdf5b1b1b        3 months ago        643MB

**Comment by spogrebna** [comment]
1. I believe, your license won't work with XAP 12.0.1.  This dockerfile is incompatable with 10 version even if you slightly edit it to download XAP 10 because environment variables have been renamed since XAP 11. (https://docs.gigaspaces.com/release_notes/110upgrading.html)
2. The issue was that 'd3a0pn6rx5g9yg.cloudfront.net' host is not avalible any more. I changed the url.
You should not have any error messages while building the image and all steps should succeed

**Comment by climacs** [comment]
thank you for this information @spogrebna

Cheers
Gary
